### ISSUE TITLE
After volume attached to other host, volume need to remove manually

### ISSUE THREAD

**Issue by david187** [linode/docker-volume-linode#27]
If a volume attached to a host (Host A), then exit the host A container.
Then attached the volume to the other host (host B). 
After that, exit the host B container, and try mount that volume on host A, it will return error
"error while mounting volume '': VolumeDriver.Mount: EOF"

After remove the docker dummy volume pointer, the volume can mount to host A again.
> docker volume rm [volume name]

it seem related to driver.go line 303 ?
Even the local docker api volume report volume is already exist, the mount function should ensure does it really attached.

driver.go line 303
> 	// else... linode already attached to current host
https://github.com/linode/docker-volume-linode/blob/be8f94b4eb7bd4615e550defa0cf76d98bd23ed6/driver.go

===============

Host A:
docker run -it --rm --mount volume-driver=linode,source=test-vol,destination=/test,volume-opt=size=10 alpine

#(exit container)

Host B:
docker run -it --rm --mount volume-driver=linode,source=test-vol,destination=/test,volume-opt=size=10 alpine

#(exit container)

Host A:
docker run -it --rm --mount volume-driver=linode,source=test-vol,destination=/test,volume-opt=size=10 alpine
return API error (500): error while mounting volume '': VolumeDriver.Mount: EOF

docker volume rm test-vol

**Comment by displague** [comment]
@david187 This should be addressed by https://github.com/linode/docker-volume-linode/pull/22/files#diff-749da71b40f8ff06fc9e78ce917b0cceR290 (which hasn't been fully verified).

**Comment by displague** [comment]
I've had some trouble getting that build to run correctly.  I do believe that the fix is in that branch though. I'll see about extracting it to a less cumbersome PR.

**Comment by gherkz** [comment]
Does anyone know if there are any plans to address this? It's really annoying for my docker swarm cluster on Linode. It affectively means that each service can only be deployed to one node in the cluster (unless I manually detach the volume from the other host).

I've also noticed that if the volume is attached to a running container on host B, and I remove the dummy volume pointer from host A who isn't using it, then the driver forces the volume to be detached from host B, killing the container and potentially resulting in data loss.

I really appreciate this volume driver, which has made using Linode with my docker swarm cluster possible. A solution to this would be the icing on the cake.

**Comment by gherkz** [comment]
> Sorry to bump this

Bumps are much appreciated when they come like this! Thanks for the great plugin @LBGarber - looking forward to the update 🙂.

**Comment by LBGarber** [comment]
After some further investigation we've found a better method of handling the volume attach/detach issue.

I have put up a new [pull request](#38) to resolve this issue. In addition to fixing the attach/detach issue, this change should resolve the force-detaching issue you discovered!

Feel free to read up on the [pull request](#38) for more details!

cc @gherkz

**Comment by LBGarber** [comment]
No problem at all @gherkz! 

Release `v0.16.0` has just been tagged and released to Docker Hub.

Let me know if you run into any issues!

**Comment by gherkz** [comment]
Thanks @LBGarber!

I just tried the new version and I'm afraid I'm having a few problems with it in my docker swarm cluster. Perhaps you can help me with them? (Sorry for the long post, just didn't want to miss anything)

I had a few pain points with the upgrade. I managed to resolve most of them, but they might the upgrade painful for other customers as well:
1. When upgrading the plugin, I have to disable it first. In order to disable it, I have to remove all volume "pointers" using `docker volume rm`. For some reason, this seems to detach the volume from _other_ Linodes (this behaviour appears to remain after the upgrade as well). To work around this, I made sure no containers were running on the node and did `docker plugin disable --force linode` which appeared to let me upgrade it without removing the volume pointer, but had its own issues (see my last point).
2. I now seem to have to set the linode-label setting or I get the error `Error response from daemon: dial unix /run/docker/plugins/c06c06f0645812ab16604d7a2566471ca380eeac0f8bab001677f0a97c1dfcbd/linode.sock: connect: no such file or directory`. This appears to be a breaking change, with a rather unhelpful error if it is missing. Re-reading the readme helped me work out that it is now a required setting, but other users might not think to do that.
2. The required API token scopes seem to have changed. I started getting the error `VolumeDriver.Mount: failed to attach volume: [401] Your OAuth token is not authorized to use this endpoint`. I used to just have read/write for volumes and linodes. I've now made a new token with read/write for everything, which appears to be working. Do you know what specific scopes I need so I can reduce the access level?
3. After I fixed the API token error, I started getting the error `VolumeDriver.Mount: failed to attach volume: volume is currently in use by linode id 13486472`. Indeed, the volume _was_ attached to linode ID 13486472, but it wasn't in use by any containers. In fact, I had this error when trying to start a service on linode 13486472 itself 🤔. The solution: I had to remove the old volume "pointer" for all volumes on all my Linodes, which seemed to reset it somehow. This meant I had to make sure _no_ containers were using the volumes on any host due to the first point.

After resolving the above errors, my docker swarm services appeared to start correctly, and I managed to move a couple of containers to different hosts successfully (something I wasn't able to do before without manually detaching the volume 🎉❤️). However, after a while, I seem to start getting errors:
* `starting container failed: error while mounting volume '/var/lib/docker/plugins/2d7965a7e19d798e908ec629d874d567233e503dd06f103b08bfd4e86e2da7a7/rootfs': Post "http://%2Frun%2Fdocker%2Fplugins%2F2d7965a7e19d798e908ec629d874d567233e503dd06f103b08bfd4e86e2da7a7%2Flinode.sock/VolumeDriver.Mount": net/http: request canceled (Client.Timeout exceeded while awaiting headers)`
* `VolumeDriver.Mount: failed to attach volume: volume is currently in use by linode id 13486472` (this one is the same as point number 3 above, but more of an ongoing issue, even when reattaching to the same linode).

These errors seem to persist and stop services from running altogether. For now, I have sadly downgraded to v0.14.104 to get up and running again. I really hope I have missed something obvious so I can upgrade again followed by posting several facepalm emojis. Do you have any ideas?

**Comment by LBGarber** [comment]
Closing because this issue seems to be resolved. Feel free to open a new issue if anything else pops up! 😃
